name: Example Workflow for Concurrency Files
run-name: ${{ github.actor }} is concurrency action
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    concurrency:
      group: staging_env
      cancel-in-progress: ${{ !contains(github.ref, 'main') }}
    steps:
      - name: first step
        run: echo "the is step."
