name: Example Workflow for Output Files
run-name: ${{ github.actor }} is Output action
on: push
jobs:
  Set-Output:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-selector
        run: echo "SELECTED_COLOR=red" >> $GITHUB_OUTPUT

      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"

      - name: GET env
        run: echo "The selected color env is $SELECTED_COLOR"
