name: Example Workflow for Environment Files
run-name: ${{ github.actor }} is demo action
on: push
env:
  name: "fifa"
jobs:
  Set-And-Use-Env-Vars:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "MY_ENV_VAR=myValue" >> $GITHUB_ENV

      - name: Use environment variable
        run: |
          echo "The value of MY_ENV_VAR is $MY_ENV_VAR"

  Use-Vars:
    needs: Set-And-Use-Env-Vars
    runs-on: ubuntu-latest
    steps:
      - name: Use variable
        run: echo "The value of MY_ENV_VAR is ${{ vars.RUNNER }}"
